/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminEscalationsRouteImport } from './routes/_authenticated/admin.escalations'
import { Route as AuthenticatedAdminListingsRouteImport } from './routes/_authenticated/admin.listings'
import { Route as AuthenticatedAdminMentorsRouteImport } from './routes/_authenticated/admin.mentors'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAptitudeRouteImport } from './routes/_authenticated/app.aptitude'
import { Route as AuthenticatedAppPreferencesRouteImport } from './routes/_authenticated/app.preferences'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedEmployerIndexRouteImport } from './routes/_authenticated/employer.index'
import { Route as AuthenticatedMentorIndexRouteImport } from './routes/_authenticated/mentor.index'
import { Route as AuthenticatedAppApplicationsIndexRouteImport } from './routes/_authenticated/app.applications.index'
import { Route as AuthenticatedAppApplicationsIdRouteImport } from './routes/_authenticated/app.applications.$id'
import { Route as AuthenticatedAppApplyListingIdRouteImport } from './routes/_authenticated/app.apply.$listingId'
import { Route as AuthenticatedAppListingsIdRouteImport } from './routes/_authenticated/app.listings.$id'
import { Route as AuthenticatedEmployerApplicationsIdRouteImport } from './routes/_authenticated/employer.applications.$id'
import { Route as AuthenticatedEmployerListingsIdRouteImport } from './routes/_authenticated/employer.listings.$id'
import { Route as AuthenticatedEmployerListingsNewRouteImport } from './routes/_authenticated/employer.listings.new'
import { Route as AuthenticatedMentorApplicationsIndexRouteImport } from './routes/_authenticated/mentor.applications.index'
import { Route as AuthenticatedMentorApplicationsIdRouteImport } from './routes/_authenticated/mentor.applications.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEscalationsRoute =
  AuthenticatedAdminEscalationsRouteImport.update({
    id: '/admin/escalations',
    path: '/admin/escalations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminListingsRoute =
  AuthenticatedAdminListingsRouteImport.update({
    id: '/admin/listings',
    path: '/admin/listings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMentorsRoute =
  AuthenticatedAdminMentorsRouteImport.update({
    id: '/admin/mentors',
    path: '/admin/mentors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAptitudeRoute =
  AuthenticatedAppAptitudeRouteImport.update({
    id: '/app/aptitude',
    path: '/app/aptitude',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPreferencesRoute =
  AuthenticatedAppPreferencesRouteImport.update({
    id: '/app/preferences',
    path: '/app/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployerIndexRoute =
  AuthenticatedEmployerIndexRouteImport.update({
    id: '/employer/',
    path: '/employer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorIndexRoute =
  AuthenticatedMentorIndexRouteImport.update({
    id: '/mentor/',
    path: '/mentor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppApplicationsIndexRoute =
  AuthenticatedAppApplicationsIndexRouteImport.update({
    id: '/app/applications/',
    path: '/app/applications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppApplicationsIdRoute =
  AuthenticatedAppApplicationsIdRouteImport.update({
    id: '/app/applications/$id',
    path: '/app/applications/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppApplyListingIdRoute =
  AuthenticatedAppApplyListingIdRouteImport.update({
    id: '/app/apply/$listingId',
    path: '/app/apply/$listingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppListingsIdRoute =
  AuthenticatedAppListingsIdRouteImport.update({
    id: '/app/listings/$id',
    path: '/app/listings/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerApplicationsIdRoute =
  AuthenticatedEmployerApplicationsIdRouteImport.update({
    id: '/employer/applications/$id',
    path: '/employer/applications/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerListingsIdRoute =
  AuthenticatedEmployerListingsIdRouteImport.update({
    id: '/employer/listings/$id',
    path: '/employer/listings/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerListingsNewRoute =
  AuthenticatedEmployerListingsNewRouteImport.update({
    id: '/employer/listings/new',
    path: '/employer/listings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorApplicationsIndexRoute =
  AuthenticatedMentorApplicationsIndexRouteImport.update({
    id: '/mentor/applications/',
    path: '/mentor/applications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorApplicationsIdRoute =
  AuthenticatedMentorApplicationsIdRouteImport.update({
    id: '/mentor/applications/$id',
    path: '/mentor/applications/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/escalations': typeof AuthenticatedAdminEscalationsRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/mentors': typeof AuthenticatedAdminMentorsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/app/aptitude': typeof AuthenticatedAppAptitudeRoute
  '/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/employer/': typeof AuthenticatedEmployerIndexRoute
  '/mentor/': typeof AuthenticatedMentorIndexRoute
  '/app/applications/$id': typeof AuthenticatedAppApplicationsIdRoute
  '/app/apply/$listingId': typeof AuthenticatedAppApplyListingIdRoute
  '/app/listings/$id': typeof AuthenticatedAppListingsIdRoute
  '/employer/applications/$id': typeof AuthenticatedEmployerApplicationsIdRoute
  '/employer/listings/$id': typeof AuthenticatedEmployerListingsIdRoute
  '/employer/listings/new': typeof AuthenticatedEmployerListingsNewRoute
  '/mentor/applications/$id': typeof AuthenticatedMentorApplicationsIdRoute
  '/app/applications/': typeof AuthenticatedAppApplicationsIndexRoute
  '/mentor/applications/': typeof AuthenticatedMentorApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/escalations': typeof AuthenticatedAdminEscalationsRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/mentors': typeof AuthenticatedAdminMentorsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/app/aptitude': typeof AuthenticatedAppAptitudeRoute
  '/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/employer': typeof AuthenticatedEmployerIndexRoute
  '/mentor': typeof AuthenticatedMentorIndexRoute
  '/app/applications/$id': typeof AuthenticatedAppApplicationsIdRoute
  '/app/apply/$listingId': typeof AuthenticatedAppApplyListingIdRoute
  '/app/listings/$id': typeof AuthenticatedAppListingsIdRoute
  '/employer/applications/$id': typeof AuthenticatedEmployerApplicationsIdRoute
  '/employer/listings/$id': typeof AuthenticatedEmployerListingsIdRoute
  '/employer/listings/new': typeof AuthenticatedEmployerListingsNewRoute
  '/mentor/applications/$id': typeof AuthenticatedMentorApplicationsIdRoute
  '/app/applications': typeof AuthenticatedAppApplicationsIndexRoute
  '/mentor/applications': typeof AuthenticatedMentorApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/admin/escalations': typeof AuthenticatedAdminEscalationsRoute
  '/_authenticated/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/_authenticated/admin/mentors': typeof AuthenticatedAdminMentorsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/app/aptitude': typeof AuthenticatedAppAptitudeRoute
  '/_authenticated/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/employer/': typeof AuthenticatedEmployerIndexRoute
  '/_authenticated/mentor/': typeof AuthenticatedMentorIndexRoute
  '/_authenticated/app/applications/$id': typeof AuthenticatedAppApplicationsIdRoute
  '/_authenticated/app/apply/$listingId': typeof AuthenticatedAppApplyListingIdRoute
  '/_authenticated/app/listings/$id': typeof AuthenticatedAppListingsIdRoute
  '/_authenticated/employer/applications/$id': typeof AuthenticatedEmployerApplicationsIdRoute
  '/_authenticated/employer/listings/$id': typeof AuthenticatedEmployerListingsIdRoute
  '/_authenticated/employer/listings/new': typeof AuthenticatedEmployerListingsNewRoute
  '/_authenticated/mentor/applications/$id': typeof AuthenticatedMentorApplicationsIdRoute
  '/_authenticated/app/applications/': typeof AuthenticatedAppApplicationsIndexRoute
  '/_authenticated/mentor/applications/': typeof AuthenticatedMentorApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin/escalations'
    | '/admin/listings'
    | '/admin/mentors'
    | '/admin/reports'
    | '/app/aptitude'
    | '/app/preferences'
    | '/app/profile'
    | '/admin/'
    | '/app/'
    | '/employer/'
    | '/mentor/'
    | '/app/applications/$id'
    | '/app/apply/$listingId'
    | '/app/listings/$id'
    | '/employer/applications/$id'
    | '/employer/listings/$id'
    | '/employer/listings/new'
    | '/mentor/applications/$id'
    | '/app/applications/'
    | '/mentor/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin/escalations'
    | '/admin/listings'
    | '/admin/mentors'
    | '/admin/reports'
    | '/app/aptitude'
    | '/app/preferences'
    | '/app/profile'
    | '/admin'
    | '/app'
    | '/employer'
    | '/mentor'
    | '/app/applications/$id'
    | '/app/apply/$listingId'
    | '/app/listings/$id'
    | '/employer/applications/$id'
    | '/employer/listings/$id'
    | '/employer/listings/new'
    | '/mentor/applications/$id'
    | '/app/applications'
    | '/mentor/applications'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/onboarding'
    | '/_authenticated/admin/escalations'
    | '/_authenticated/admin/listings'
    | '/_authenticated/admin/mentors'
    | '/_authenticated/admin/reports'
    | '/_authenticated/app/aptitude'
    | '/_authenticated/app/preferences'
    | '/_authenticated/app/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/employer/'
    | '/_authenticated/mentor/'
    | '/_authenticated/app/applications/$id'
    | '/_authenticated/app/apply/$listingId'
    | '/_authenticated/app/listings/$id'
    | '/_authenticated/employer/applications/$id'
    | '/_authenticated/employer/listings/$id'
    | '/_authenticated/employer/listings/new'
    | '/_authenticated/mentor/applications/$id'
    | '/_authenticated/app/applications/'
    | '/_authenticated/mentor/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/escalations': {
      id: '/_authenticated/admin/escalations'
      path: '/admin/escalations'
      fullPath: '/admin/escalations'
      preLoaderRoute: typeof AuthenticatedAdminEscalationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/listings': {
      id: '/_authenticated/admin/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AuthenticatedAdminListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/mentors': {
      id: '/_authenticated/admin/mentors'
      path: '/admin/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AuthenticatedAdminMentorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/aptitude': {
      id: '/_authenticated/app/aptitude'
      path: '/app/aptitude'
      fullPath: '/app/aptitude'
      preLoaderRoute: typeof AuthenticatedAppAptitudeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/preferences': {
      id: '/_authenticated/app/preferences'
      path: '/app/preferences'
      fullPath: '/app/preferences'
      preLoaderRoute: typeof AuthenticatedAppPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/': {
      id: '/_authenticated/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof AuthenticatedEmployerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/': {
      id: '/_authenticated/mentor/'
      path: '/mentor'
      fullPath: '/mentor/'
      preLoaderRoute: typeof AuthenticatedMentorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/applications/': {
      id: '/_authenticated/app/applications/'
      path: '/app/applications'
      fullPath: '/app/applications/'
      preLoaderRoute: typeof AuthenticatedAppApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/applications/$id': {
      id: '/_authenticated/app/applications/$id'
      path: '/app/applications/$id'
      fullPath: '/app/applications/$id'
      preLoaderRoute: typeof AuthenticatedAppApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/apply/$listingId': {
      id: '/_authenticated/app/apply/$listingId'
      path: '/app/apply/$listingId'
      fullPath: '/app/apply/$listingId'
      preLoaderRoute: typeof AuthenticatedAppApplyListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/listings/$id': {
      id: '/_authenticated/app/listings/$id'
      path: '/app/listings/$id'
      fullPath: '/app/listings/$id'
      preLoaderRoute: typeof AuthenticatedAppListingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/applications/$id': {
      id: '/_authenticated/employer/applications/$id'
      path: '/employer/applications/$id'
      fullPath: '/employer/applications/$id'
      preLoaderRoute: typeof AuthenticatedEmployerApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/listings/$id': {
      id: '/_authenticated/employer/listings/$id'
      path: '/employer/listings/$id'
      fullPath: '/employer/listings/$id'
      preLoaderRoute: typeof AuthenticatedEmployerListingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/listings/new': {
      id: '/_authenticated/employer/listings/new'
      path: '/employer/listings/new'
      fullPath: '/employer/listings/new'
      preLoaderRoute: typeof AuthenticatedEmployerListingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/applications/': {
      id: '/_authenticated/mentor/applications/'
      path: '/mentor/applications'
      fullPath: '/mentor/applications/'
      preLoaderRoute: typeof AuthenticatedMentorApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/applications/$id': {
      id: '/_authenticated/mentor/applications/$id'
      path: '/mentor/applications/$id'
      fullPath: '/mentor/applications/$id'
      preLoaderRoute: typeof AuthenticatedMentorApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAdminEscalationsRoute: typeof AuthenticatedAdminEscalationsRoute
  AuthenticatedAdminListingsRoute: typeof AuthenticatedAdminListingsRoute
  AuthenticatedAdminMentorsRoute: typeof AuthenticatedAdminMentorsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAppAptitudeRoute: typeof AuthenticatedAppAptitudeRoute
  AuthenticatedAppPreferencesRoute: typeof AuthenticatedAppPreferencesRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedEmployerIndexRoute: typeof AuthenticatedEmployerIndexRoute
  AuthenticatedMentorIndexRoute: typeof AuthenticatedMentorIndexRoute
  AuthenticatedAppApplicationsIdRoute: typeof AuthenticatedAppApplicationsIdRoute
  AuthenticatedAppApplyListingIdRoute: typeof AuthenticatedAppApplyListingIdRoute
  AuthenticatedAppListingsIdRoute: typeof AuthenticatedAppListingsIdRoute
  AuthenticatedEmployerApplicationsIdRoute: typeof AuthenticatedEmployerApplicationsIdRoute
  AuthenticatedEmployerListingsIdRoute: typeof AuthenticatedEmployerListingsIdRoute
  AuthenticatedEmployerListingsNewRoute: typeof AuthenticatedEmployerListingsNewRoute
  AuthenticatedMentorApplicationsIdRoute: typeof AuthenticatedMentorApplicationsIdRoute
  AuthenticatedAppApplicationsIndexRoute: typeof AuthenticatedAppApplicationsIndexRoute
  AuthenticatedMentorApplicationsIndexRoute: typeof AuthenticatedMentorApplicationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAdminEscalationsRoute: AuthenticatedAdminEscalationsRoute,
  AuthenticatedAdminListingsRoute: AuthenticatedAdminListingsRoute,
  AuthenticatedAdminMentorsRoute: AuthenticatedAdminMentorsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAppAptitudeRoute: AuthenticatedAppAptitudeRoute,
  AuthenticatedAppPreferencesRoute: AuthenticatedAppPreferencesRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedEmployerIndexRoute: AuthenticatedEmployerIndexRoute,
  AuthenticatedMentorIndexRoute: AuthenticatedMentorIndexRoute,
  AuthenticatedAppApplicationsIdRoute: AuthenticatedAppApplicationsIdRoute,
  AuthenticatedAppApplyListingIdRoute: AuthenticatedAppApplyListingIdRoute,
  AuthenticatedAppListingsIdRoute: AuthenticatedAppListingsIdRoute,
  AuthenticatedEmployerApplicationsIdRoute:
    AuthenticatedEmployerApplicationsIdRoute,
  AuthenticatedEmployerListingsIdRoute: AuthenticatedEmployerListingsIdRoute,
  AuthenticatedEmployerListingsNewRoute: AuthenticatedEmployerListingsNewRoute,
  AuthenticatedMentorApplicationsIdRoute:
    AuthenticatedMentorApplicationsIdRoute,
  AuthenticatedAppApplicationsIndexRoute:
    AuthenticatedAppApplicationsIndexRoute,
  AuthenticatedMentorApplicationsIndexRoute:
    AuthenticatedMentorApplicationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
